### ISSUE TITLE
getSizeViewportRect Contain - Cover

### ISSUE THREAD

**Issue by martifenosa** [jocabola/web-packages#1]
Returns new image size in cover mode. 
Contain mode should be also available.

**Comment by jocabola** [comment]
[Check this out](https://github.com/jocabola/web-packages/blob/master/gfx/src/utils/GfxUtils.ts). I have added `FitType` and now fit rect function and its related functions receive a fit parameter with `cover` as default. You can simply pass `'contain'` into it now. Please check & test.
